#!/bin/bash

# Check whether all the necessary gems are installed.
# If not, just run the command normally without `bundle exec`.
if bundle check &> /dev/null; then
  bundle exec "$@"
else
  exec "$@"
fi
